# Use postgres/example user/password credentials
version: '3.1'

services:
  auth_db:
    image: postgres:11.6-alpine
    container_name: selfi_auth_wdb_dev
    ports:
      - 9992:5432
    environment:
      POSTGRES_DB: auth_dev
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: yIe7fq4h#k!Ktn&shDo5r@Jt
    volumes:
      - selfi_dbdata:/var/lib/postgresql/data/auth

volumes:
  selfi_dbdata: